In [42]:
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [40]:
df=pd.read_csv("C:/Users/HRISHI/Downloads/Simple_Linear_Regression_Sales_data.csv")

In [4]:
df

TV  Sales
0    230.1   22.1
1     44.5   10.4
2     17.2    9.3
3    151.5   18.5
4    180.8   12.9
5      8.7    7.2
6     57.5   11.8
7    120.2   13.2
8      8.6    4.8
9    199.8   10.6
10    66.1    8.6
11   214.7   17.4
12    23.8    9.2
13    97.5    9.7
14   204.1   19.0
15   195.4   22.4
16    67.8   12.5
17   281.4   24.4
18    69.2   11.3
19   147.3   14.6
20   218.4   18.0
21   237.4   12.5
22    13.2    5.6
23   228.3   15.5
24    62.3    9.7
25   262.9   12.0
26   142.9   15.0
27   240.1   15.9
28   248.8   18.9
29    70.6   10.5
..     ...    ...
170   50.0    8.4
171  164.5   14.5
172   19.6    7.6
173  168.4   11.7
174  222.4   11.5
175  276.9   27.0
176  248.4   20.2
177  170.2   11.7
178  276.7   11.8
179  165.6   12.6
180  156.6   10.5
181  218.5   12.2
182   56.2    8.7
183  287.6   26.2
184  253.8   17.6
185  205.0   22.6
186  139.5   10.3
187  191.1   17.3
188  286.0   15.9
189   18.7    6.7
190   39.5   10.8
191   75.5    9.9
192   17.2    5.9
193  166.8   19.6
194  149.7   17.3
195   38.2    7.6
196   94.2    9.7
197  177.0   12.8
198  283.6   25.5
199  232.1   13.4

[200 rows x 2 columns]

In [5]:
df.head()

TV  Sales
0  230.1   22.1
1   44.5   10.4
2   17.2    9.3
3  151.5   18.5
4  180.8   12.9

In [6]:
df.keys()

Index(['TV', 'Sales'], dtype='object')

In [8]:
df.shape

(200, 2)

In [18]:
x=df['TV'].values.reshape(-1,1)
y=df['Sales'].values.reshape(-1,1)


In [23]:
type(x)
print(x)

[[230.1]
 [ 44.5]
 [ 17.2]
 [151.5]
 [180.8]
 [  8.7]
 [ 57.5]
 [120.2]
 [  8.6]
 [199.8]
 [ 66.1]
 [214.7]
 [ 23.8]
 [ 97.5]
 [204.1]
 [195.4]
 [ 67.8]
 [281.4]
 [ 69.2]
 [147.3]
 [218.4]
 [237.4]
 [ 13.2]
 [228.3]
 [ 62.3]
 [262.9]
 [142.9]
 [240.1]
 [248.8]
 [ 70.6]
 [292.9]
 [112.9]
 [ 97.2]
 [265.6]
 [ 95.7]
 [290.7]
 [266.9]
 [ 74.7]
 [ 43.1]
 [228. ]
 [202.5]
 [177. ]
 [293.6]
 [206.9]
 [ 25.1]
 [175.1]
 [ 89.7]
 [239.9]
 [227.2]
 [ 66.9]
 [199.8]
 [100.4]
 [216.4]
 [182.6]
 [262.7]
 [198.9]
 [  7.3]
 [136.2]
 [210.8]
 [210.7]
 [ 53.5]
 [261.3]
 [239.3]
 [102.7]
 [131.1]
 [ 69. ]
 [ 31.5]
 [139.3]
 [237.4]
 [216.8]
 [199.1]
 [109.8]
 [ 26.8]
 [129.4]
 [213.4]
 [ 16.9]
 [ 27.5]
 [120.5]
 [  5.4]
 [116. ]
 [ 76.4]
 [239.8]
 [ 75.3]
 [ 68.4]
 [213.5]
 [193.2]
 [ 76.3]
 [110.7]
 [ 88.3]
 [109.8]
 [134.3]
 [ 28.6]
 [217.7]
 [250.9]
 [107.4]
 [163.3]
 [197.6]
 [184.9]
 [289.7]
 [135.2]
 [222.4]
 [296.4]
 [280.2]
 [187.9]
 [238.2]
 [137.9]
 [ 25. ]
 [ 90.4]
 [ 13.1]
 [255.4]
 [225.8]
 

In [20]:
y

array([[22.1],
       [10.4],
       [ 9.3],
       [18.5],
       [12.9],
       [ 7.2],
       [11.8],
       [13.2],
       [ 4.8],
       [10.6],
       [ 8.6],
       [17.4],
       [ 9.2],
       [ 9.7],
       [19. ],
       [22.4],
       [12.5],
       [24.4],
       [11.3],
       [14.6],
       [18. ],
       [12.5],
       [ 5.6],
       [15.5],
       [ 9.7],
       [12. ],
       [15. ],
       [15.9],
       [18.9],
       [10.5],
       [21.4],
       [11.9],
       [ 9.6],
       [17.4],
       [ 9.5],
       [12.8],
       [25.4],
       [14.7],
       [10.1],
       [21.5],
       [16.6],
       [17.1],
       [20.7],
       [12.9],
       [ 8.5],
       [14.9],
       [10.6],
       [23.2],
       [14.8],
       [ 9.7],
       [11.4],
       [10.7],
       [22.6],
       [21.2],
       [20.2],
       [23.7],
       [ 5.5],
       [13.2],
       [23.8],
       [18.4],
       [ 8.1],
       [24.2],
       [15.7],
       [14. ],
       [18. ],
       [ 9.3],
       [ 9

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [47]:
reg=LinearRegression()

In [48]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [64]:
prediction=reg.predict(x_test)

In [65]:
prediction

array([[16.84129141],
       [ 7.56876758],
       [17.194749  ],
       [20.18766263],
       [17.10294183],
       [13.93100422],
       [15.8176415 ],
       [16.29962912],
       [17.12130326],
       [ 7.95894804],
       [20.46767449],
       [10.20363326],
       [ 7.94517696],
       [17.29114652],
       [17.70427877],
       [11.88370441],
       [18.89318158],
       [ 7.41728575],
       [18.26430249],
       [16.57964098],
       [15.79009935],
       [ 7.20153891],
       [19.16401272],
       [12.25093308],
       [20.03159044],
       [ 8.03239377],
       [ 8.34453814],
       [ 9.21211586],
       [18.18167604],
       [ 8.06911664],
       [13.21490833],
       [17.6354234 ],
       [ 8.43175495],
       [ 8.48224889],
       [20.51357807],
       [19.8709279 ],
       [10.85087379],
       [20.21979514],
       [11.28695783],
       [17.37836333]])

In [60]:
y_test

array([[18.4],
       [ 7.2],
       [18. ],
       [25.5],
       [22.6],
       [14.6],
       [14.9],
       [23.7],
       [22.3],
       [ 9.3],
       [25.4],
       [ 8.6],
       [ 8.7],
       [20.1],
       [19.7],
       [14. ],
       [19.8],
       [ 5.3],
       [21.8],
       [22.6],
       [15.6],
       [ 1.6],
       [24.2],
       [16. ],
       [14.8],
       [ 7. ],
       [ 9.5],
       [10.4],
       [23.2],
       [ 7.6],
       [12.9],
       [21.5],
       [ 6.9],
       [ 7.3],
       [12.8],
       [11.8],
       [ 8.8],
       [15. ],
       [10.6],
       [11.5]])

In [61]:
r2_score(y_test, prediction)

0.642804477396066